### ISSUE TITLE
Install the OS 404

### ISSUE THREAD

**Issue by neilcsmith-net** [Tooloop/Tooloop-OS-Website#5]
Just pointing someone at the website and noticed the `Install the OS` link on the frontpage is currently a 404.

**Comment by vollstock** [comment]
hehe, nice. Will fix that later today :-) Thanks for the notice!

**Comment by vollstock** [comment]
fixed in https://github.com/vollstock/Tooloop-Website/commit/2bae749ad8c249fa040893653e50071547d1eaef
